
INSERT INTO groceries (item) 
VALUES 
('Bananas'),
('Snack apples'),
('Honey crisp apples'),
('Celery'),
('Carrots (might have)'),
('Red pepper'),
('Fresh dill'),
('Red onion'),
('One lemon'),
('Cilantro'),
('Green onion'),
('Garlic'),
('Red potatoes'),
('Two avocados '),
('Curly kale'),
('Cashew butter'),
('Macaroni noodles'),
('chickpeas'),
('Pickles'),
('Pickled jalapeños'),
('Powdered sugar'),
('Cream cheese'),
('Frozen peas (might have)'),
('Gluten free brown rice fusilli'),
('Coconut milk'),
('Gf AP flour'),
('Cane sugar'),
('Choc chips');

